name: Reusable Yocto Build

on:
  workflow_call:
    inputs:
      toolchain-release-tag:
        description: 'The release tag from which to download the toolchain'
        required: true
        type: string
      toolchain-filename:
        description: 'The exact filename of the toolchain installer script'
        required: true
        type: string
      toolchain-install-dir:
        description: 'The destination directory for the toolchain installation'
        required: true
        type: string

      # Receives a JSON array of preset objects to build
      build-presets-json:
        description: 'A JSON array of preset objects to build'
        required: true
        type: string

    secrets:
      pat-token:
        description: 'Personal Access Token to download the toolchain'
        required: true

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 10

    # Runs a job for each item in the 'build-presets-json' input
    strategy:
      fail-fast: false
      matrix:
        # e.g., { "name": "tx", "artifact_name": "LIN_TX", "artifact_path": "build/release/LIN_TX" }
        preset: ${{ fromJson(inputs.build-presets-json) }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          submodules: 'recursive'

      - name: Install base dependencies
        run: sudo apt-get update && sudo apt-get install -y cmake

      - name: Download Yocto SDK
        run: >
          gh release download ${{ inputs.toolchain-release-tag }}
          -p '${{ inputs.toolchain-filename }}'
          --repo KEPM-PGSEnergy/orion-bsp
        env:
          GITHUB_TOKEN: ${{ secrets.pat-token }}

      - name: Install Yocto SDK
        run: |
          INSTALLER_SCRIPT="${{ inputs.toolchain-filename }}"
          chmod +x "${INSTALLER_SCRIPT}"
          sudo ./"${INSTALLER_SCRIPT}" -y -d ${{ inputs.toolchain-install-dir }}

      - name: Configure CMake
        run: cmake --preset ${{ matrix.preset.name }}

      - name: Build
        run: cmake --build --preset ${{ matrix.preset.name }}

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.preset.artifact_name }}
          path: ${{ matrix.preset.artifact_path }}
